name: Build macOS .app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Build .app with PyInstaller
        run: |
          pyinstaller --onefile --windowed \
          --add-data "logologotype.jpg:." \
          qt_template.py

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutopeerMacApp
          path: dist/*.app
